"""
remediation.py
==============

Task 2, Phase 4: AI Remediation Engine + Secure Coding Recommendations.

This module deliberately does **not** duplicate the entity_type ->
remediation-advice table Phase 2 already built in
`scanner.ai.recommendations`; it imports and reuses
`recommendation_for_entity` / `build_recommendations` directly, and
only *adds* the two things Phase 2 didn't need: an OWASP Top 10
reference and a CWE mapping, plus a short, general secure-coding
best-practice statement.

Every recommendation, OWASP reference, and CWE mapping below is a
static lookup -- nothing here is generated by an AI model, and results
are identical across runs for the same input (per project
requirements: "Do NOT generate hallucinated code. Recommendations must
be deterministic.").
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from scanner.ai.recommendations import build_recommendations, recommendation_for_entity


@dataclass(frozen=True, slots=True)
class _SecureCodingReference:
    """Static OWASP/CWE/best-practice reference for one entity type."""

    owasp: str
    cwe: str
    best_practice: str
    references: tuple[str, ...]


_DEFAULT_REFERENCE = _SecureCodingReference(
    owasp="OWASP A02:2021 - Cryptographic Failures",
    cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
    best_practice=(
        "Never store values that identify a real person or system "
        "directly in source, configuration, or test data; use "
        "synthetic data or a secrets manager instead."
    ),
    references=(
        "https://owasp.org/Top10/",
        "https://cwe.mitre.org/data/definitions/200.html",
    ),
)

# ---------------------------------------------------------------------------
# entity_type -> secure coding reference.
#
# Covers exactly the entity types `scanner.pii_detector` classifies
# into a severity. Anything else falls back to `_DEFAULT_REFERENCE`.
# ---------------------------------------------------------------------------
_ENTITY_REFERENCES: dict[str, _SecureCodingReference] = {
    "CREDIT_CARD": _SecureCodingReference(
        owasp="OWASP A02:2021 - Cryptographic Failures",
        cwe="CWE-312: Cleartext Storage of Sensitive Information",
        best_practice=(
            "Never store raw payment card numbers in code, config, or "
            "logs; tokenize via a PCI-compliant payment processor."
        ),
        references=(
            "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            "https://cwe.mitre.org/data/definitions/312.html",
        ),
    ),
    "CRYPTO": _SecureCodingReference(
        owasp="OWASP A02:2021 - Cryptographic Failures",
        cwe="CWE-798: Use of Hard-coded Credentials",
        best_practice=(
            "Never store private keys or wallet credentials in source; "
            "load them from a hardware wallet, HSM, or secrets manager."
        ),
        references=(
            "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            "https://cwe.mitre.org/data/definitions/798.html",
        ),
    ),
    "US_SSN": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode government identifiers; use synthetic "
            "identifiers in tests and restrict real values to "
            "access-controlled systems."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "US_ITIN": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode taxpayer identifiers; use synthetic values "
            "in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "US_PASSPORT": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode passport numbers; use synthetic identity "
            "documents in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "US_BANK_NUMBER": _SecureCodingReference(
        owasp="OWASP A02:2021 - Cryptographic Failures",
        cwe="CWE-312: Cleartext Storage of Sensitive Information",
        best_practice=(
            "Never hardcode bank account/routing numbers; use a "
            "sandbox account and secrets management for anything real."
        ),
        references=(
            "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            "https://cwe.mitre.org/data/definitions/312.html",
        ),
    ),
    "UK_NHS": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode health-system identifiers; use synthetic "
            "patient data in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "IBAN_CODE": _SecureCodingReference(
        owasp="OWASP A02:2021 - Cryptographic Failures",
        cwe="CWE-312: Cleartext Storage of Sensitive Information",
        best_practice=(
            "Never hardcode IBANs; use sandbox/test IBANs and secrets "
            "management for anything real."
        ),
        references=(
            "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
            "https://cwe.mitre.org/data/definitions/312.html",
        ),
    ),
    "MEDICAL_LICENSE": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode medical license numbers; use synthetic "
            "practitioner data in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "IN_AADHAAR": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode national identifiers; use synthetic "
            "identifiers in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "IN_PASSPORT": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode passport numbers; use synthetic identity "
            "documents in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "EMAIL_ADDRESS": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        best_practice=(
            "Use synthetic example addresses (e.g. user@example.com) "
            "in code, fixtures, and documentation."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/200.html",
        ),
    ),
    "PHONE_NUMBER": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        best_practice=(
            "Use a reserved test number range (e.g. 555-01xx) instead "
            "of real phone numbers."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/200.html",
        ),
    ),
    "IP_ADDRESS": _SecureCodingReference(
        owasp="OWASP A05:2021 - Security Misconfiguration",
        cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        best_practice=(
            "Move environment-specific IP addresses into configuration "
            "or secrets management rather than hardcoding in source."
        ),
        references=(
            "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
            "https://cwe.mitre.org/data/definitions/200.html",
        ),
    ),
    "PERSON": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Use synthetic names in code, comments, and test fixtures."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "ORGANIZATION": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        best_practice=(
            "Avoid committing confidential customer, partner, vendor, "
            "supplier, or internal project names; use synthetic "
            "organization names in source, documentation, logs, and "
            "test datasets unless the names are intentionally public."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/200.html",
        ),
    ),
    "LOCATION": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Use synthetic addresses/locations in test data instead of "
            "real, individual-linked locations."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "US_DRIVER_LICENSE": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Never hardcode driver's license numbers; use synthetic "
            "identity documents in tests."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "URL": _SecureCodingReference(
        owasp="OWASP A05:2021 - Security Misconfiguration",
        cwe="CWE-200: Exposure of Sensitive Information to an Unauthorized Actor",
        best_practice=(
            "Move environment-specific or credentialed URLs into "
            "configuration/secrets rather than hardcoding in source."
        ),
        references=(
            "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
            "https://cwe.mitre.org/data/definitions/200.html",
        ),
    ),
    "DATE_TIME": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Use synthetic dates in test data if a date is tied to a "
            "real individual (e.g. a date of birth)."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
    "NRP": _SecureCodingReference(
        owasp="OWASP A01:2021 - Broken Access Control",
        cwe="CWE-359: Exposure of Private Personal Information to an Unauthorized Actor",
        best_practice=(
            "Avoid recording real, individual-linked nationality/"
            "religious/political detail in code, fixtures, or logs."
        ),
        references=(
            "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
            "https://cwe.mitre.org/data/definitions/359.html",
        ),
    ),
}


def secure_coding_reference_for_entity(entity_type: str) -> dict[str, Any]:
    """
    Return the static OWASP/CWE/best-practice reference for an entity type.

    Args:
        entity_type: The Presidio entity type, e.g. "EMAIL_ADDRESS".

    Returns:
        A dict with `owasp`, `cwe`, `best_practice`, and `references`
        (a list of URLs).
    """
    ref = _ENTITY_REFERENCES.get(entity_type, _DEFAULT_REFERENCE)
    return {
        "owasp": ref.owasp,
        "cwe": ref.cwe,
        "best_practice": ref.best_practice,
        "references": list(ref.references),
    }


class RemediationEngine:
    """
    Builds remediation recommendations and secure-coding references.

    Deliberately thin: the entity_type -> remediation-advice mapping
    itself lives in `scanner.ai.recommendations` (Phase 2) and is
    reused, not duplicated.
    """

    def remediation_for_finding(self, finding: dict[str, Any]) -> dict[str, Any]:
        """
        Build the remediation entry for a single finding.

        Args:
            finding: A single finding dict (must include `entity_type`;
                ideally already enriched with a `finding_id`).

        Returns:
            A dict with `finding_id`, `entity_type`, `severity`,
            `recommendation` (reused from Phase 2), and the secure
            coding reference fields (`owasp`, `cwe`, `best_practice`,
            `references`).
        """
        entity_type = finding.get("entity_type", "UNKNOWN")
        secure_coding = secure_coding_reference_for_entity(entity_type)
        return {
            "finding_id": finding.get("finding_id"),
            "entity_type": entity_type,
            "severity": finding.get("severity"),
            "recommendation": recommendation_for_entity(entity_type),
            **secure_coding,
        }

    def build_secure_coding_recommendations(
        self, findings: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """
        Derive deduplicated, severity-ordered secure coding recommendations.

        Reuses `scanner.ai.recommendations.build_recommendations` for
        the entity-type selection, ordering, and remediation text, and
        adds the OWASP/CWE/best-practice reference to each entry.

        Args:
            findings: The `findings` list from a Task 2 Phase 1 JSON
                report.

        Returns:
            A list of dicts, one per distinct `entity_type` actually
            present in `findings`, each with `entity_type`, `severity`,
            `recommendation`, `owasp`, `cwe`, `best_practice`, and
            `references` -- ordered highest severity first, exactly as
            `build_recommendations` orders them.
        """
        base_recommendations = build_recommendations(findings)
        enriched: list[dict[str, Any]] = []
        for item in base_recommendations:
            secure_coding = secure_coding_reference_for_entity(item["entity_type"])
            enriched.append({**item, **secure_coding})
        return enriched
