"""
root_cause.py
=============

Task 2, Phase 4: Root Cause Analysis Engine.

For every finding in a Task 2 Phase 1 JSON report, derives a
deterministic explanation of *why* it was flagged, *where* it lives,
and *what developer mistake* likely produced it.

This module performs no detection of its own. It only annotates
findings that `scanner.pii_detector` already produced, using fields
already present in the report (`entity_type`, `severity`,
`confidence_score`, `file`, `line_number`) plus a static, reviewable
narrative table below. Nothing here is generated by an AI model or a
call to any external service; the same finding always produces the
same root-cause analysis.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from scanner.intelligence.categories import categorize_entity
from scanner.intelligence.finding_ids import attach_finding_ids


@dataclass(frozen=True, slots=True)
class _EntityNarrative:
    """Static, per-entity-type root-cause narrative."""

    root_cause: str
    why_detected: str
    developer_mistake: str
    security_impact: str


_DEFAULT_NARRATIVE = _EntityNarrative(
    root_cause=(
        "A value matching this entity type was committed directly into "
        "source, configuration, or test data instead of being kept out "
        "of the repository entirely."
    ),
    why_detected=(
        "Microsoft Presidio's analyzer matched this text against its "
        "recognizer for this entity type at or above the configured "
        "confidence threshold."
    ),
    developer_mistake=(
        "Using a real or realistic value during development/testing "
        "instead of synthetic test data, or logging/echoing a real "
        "value for debugging purposes."
    ),
    security_impact=(
        "Any sensitive value committed to source control remains "
        "recoverable from repository history even after later removal, "
        "and may be exposed to anyone with read access to the repo."
    ),
)

# ---------------------------------------------------------------------------
# entity_type -> narrative.
#
# Covers exactly the entity types `scanner.pii_detector` classifies
# into a severity. Anything else falls back to `_DEFAULT_NARRATIVE`
# rather than fabricating entity-specific detail.
# ---------------------------------------------------------------------------
_ENTITY_NARRATIVES: dict[str, _EntityNarrative] = {
    "CREDIT_CARD": _EntityNarrative(
        root_cause=(
            "A payment card number was committed directly into source, "
            "configuration, or test data instead of being handled "
            "exclusively by a PCI-compliant payment processor."
        ),
        why_detected=(
            "Presidio's pattern- and checksum-based recognizer matched a "
            "value structurally consistent with a payment card number."
        ),
        developer_mistake=(
            "Using a real (or realistic) card number for local testing "
            "or debugging instead of a card network's published test "
            "number range."
        ),
        security_impact=(
            "Exposure of payment card data in a repository is a PCI-DSS "
            "violation and a direct financial-fraud risk."
        ),
    ),
    "CRYPTO": _EntityNarrative(
        root_cause=(
            "A cryptocurrency wallet address or private key was "
            "committed directly into source instead of being retrieved "
            "from secure key storage at runtime."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a crypto wallet address/key."
        ),
        developer_mistake=(
            "Pasting a real wallet address or key into code or a config "
            "file for convenience during development."
        ),
        security_impact=(
            "Exposed wallet keys can be used to irreversibly move funds; "
            "unlike a password, a crypto private key cannot be revoked."
        ),
    ),
    "US_SSN": _EntityNarrative(
        root_cause=(
            "A U.S. Social Security Number was committed directly into "
            "source or test data instead of a synthetic identifier."
        ),
        why_detected=(
            "Presidio's pattern- and context-based recognizer matched a "
            "value structurally consistent with a U.S. SSN."
        ),
        developer_mistake=(
            "Copying a real individual's SSN into a fixture, seed "
            "script, or log statement while reproducing a support case."
        ),
        security_impact=(
            "SSNs are a primary identity-theft vector; exposure creates "
            "regulatory breach-notification obligations in most U.S. "
            "states."
        ),
    ),
    "US_ITIN": _EntityNarrative(
        root_cause=(
            "A U.S. Individual Taxpayer Identification Number was "
            "committed directly into source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a U.S. ITIN."
        ),
        developer_mistake=(
            "Reusing a real taxpayer record for local testing instead of "
            "synthetic data."
        ),
        security_impact=(
            "ITINs are sensitive tax-related identifiers; exposure can "
            "enable tax fraud against the affected individual."
        ),
    ),
    "US_PASSPORT": _EntityNarrative(
        root_cause=(
            "A U.S. passport number was committed directly into source "
            "or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a U.S. passport number."
        ),
        developer_mistake=(
            "Using a real customer's passport number in a fixture or "
            "support-ticket reproduction instead of synthetic data."
        ),
        security_impact=(
            "Passport numbers are government-issued identity documents; "
            "exposure supports identity theft and document fraud."
        ),
    ),
    "US_BANK_NUMBER": _EntityNarrative(
        root_cause=(
            "A U.S. bank account/routing number was committed directly "
            "into source, configuration, or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a U.S. bank account number."
        ),
        developer_mistake=(
            "Hardcoding a real bank account number for a test/demo "
            "payout instead of using a sandbox account."
        ),
        security_impact=(
            "Exposed bank account details enable unauthorized transfers "
            "or account-takeover attempts."
        ),
    ),
    "UK_NHS": _EntityNarrative(
        root_cause=(
            "A UK National Health Service number was committed directly "
            "into source or test data."
        ),
        why_detected=(
            "Presidio's pattern- and checksum-based recognizer matched a "
            "value structurally consistent with an NHS number."
        ),
        developer_mistake=(
            "Reusing a real patient record for local testing instead of "
            "synthetic health data."
        ),
        security_impact=(
            "NHS numbers link directly to an individual's medical "
            "history; exposure is a health-data (special category) "
            "privacy incident."
        ),
    ),
    "IBAN_CODE": _EntityNarrative(
        root_cause=(
            "An International Bank Account Number was committed directly "
            "into source, configuration, or test data."
        ),
        why_detected=(
            "Presidio's pattern- and checksum-based recognizer matched a "
            "value structurally consistent with an IBAN."
        ),
        developer_mistake=(
            "Hardcoding a real account's IBAN for a test transfer "
            "instead of using a sandbox/test IBAN."
        ),
        security_impact=(
            "Exposed IBANs enable unauthorized transfers or targeted "
            "phishing against the account holder."
        ),
    ),
    "MEDICAL_LICENSE": _EntityNarrative(
        root_cause=(
            "A medical license number was committed directly into "
            "source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a medical license number."
        ),
        developer_mistake=(
            "Reusing a real practitioner's license number in a fixture "
            "instead of a synthetic value."
        ),
        security_impact=(
            "Exposure can support impersonation of a licensed medical "
            "professional or fraudulent billing."
        ),
    ),
    "IN_AADHAAR": _EntityNarrative(
        root_cause=(
            "An Indian Aadhaar number was committed directly into "
            "source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with an Aadhaar number."
        ),
        developer_mistake=(
            "Reusing a real individual's Aadhaar number for local "
            "testing instead of synthetic data."
        ),
        security_impact=(
            "Aadhaar is a national identifier tied to biometric data; "
            "exposure is a severe identity-theft and privacy risk."
        ),
    ),
    "IN_PASSPORT": _EntityNarrative(
        root_cause=(
            "An Indian passport number was committed directly into "
            "source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with an Indian passport number."
        ),
        developer_mistake=(
            "Using a real customer's passport number in a fixture "
            "instead of synthetic data."
        ),
        security_impact=(
            "Passport numbers are government-issued identity documents; "
            "exposure supports identity theft and document fraud."
        ),
    ),
    "EMAIL_ADDRESS": _EntityNarrative(
        root_cause=(
            "A real email address was left in source code, comments, "
            "fixtures, or logs instead of a synthetic example address."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched standard email "
            "address syntax."
        ),
        developer_mistake=(
            "Copy-pasting a real user's email address into a test "
            "fixture, example, or debug log statement."
        ),
        security_impact=(
            "Exposed email addresses enable targeted phishing and, when "
            "combined with other findings, can support account "
            "enumeration."
        ),
    ),
    "PHONE_NUMBER": _EntityNarrative(
        root_cause=(
            "A real phone number was left in source code, fixtures, or "
            "logs instead of a synthetic/reserved test number."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched standard phone "
            "number formatting."
        ),
        developer_mistake=(
            "Using a real customer or personal phone number when writing "
            "or debugging a test case."
        ),
        security_impact=(
            "Exposed phone numbers enable targeted smishing/vishing and "
            "SIM-swap social-engineering attempts."
        ),
    ),
    "IP_ADDRESS": _EntityNarrative(
        root_cause=(
            "An IP address was hardcoded into source or configuration "
            "instead of being read from environment-specific config."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched valid IPv4/IPv6 "
            "address syntax."
        ),
        developer_mistake=(
            "Hardcoding a real internal or customer-facing IP address "
            "while debugging network connectivity."
        ),
        security_impact=(
            "Hardcoded internal IPs can reveal network topology to "
            "anyone with repository access, aiding reconnaissance."
        ),
    ),
    "PERSON": _EntityNarrative(
        root_cause=(
            "A real person's name was left in source code, comments, "
            "fixtures, or logs instead of a synthetic placeholder."
        ),
        why_detected=(
            "Presidio's NLP-based recognizer identified this text as a "
            "person name with sufficient confidence."
        ),
        developer_mistake=(
            "Using a real customer's or colleague's name in an example, "
            "test fixture, or code comment."
        ),
        security_impact=(
            "Real names, especially combined with other findings (email, "
            "phone, location), increase re-identification risk."
        ),
    ),
    "ORGANIZATION": _EntityNarrative(
        root_cause=(
            "An organization or company name was detected within "
            "repository content. While organization names are often "
            "public, they may reveal confidential customers, partners, "
            "internal projects, suppliers, or business relationships "
            "when committed into source code, documentation, logs, or "
            "datasets."
        ),
        why_detected=(
            "Presidio's NLP-based recognizer identified this text as an "
            "organization name with sufficient confidence."
        ),
        developer_mistake=(
            "Committing customer datasets, internal business "
            "documentation, vendor information, project documentation, "
            "exported reports, or test datasets containing real "
            "organizations."
        ),
        security_impact=(
            "Organization names can disclose confidential partners or "
            "customers, reveal business relationships, expose internal "
            "organizational metadata, or provide competitive "
            "intelligence."
        ),
    ),
    "LOCATION": _EntityNarrative(
        root_cause=(
            "A real, specific location (e.g. a home or office address) "
            "tied to an individual was left in source or test data."
        ),
        why_detected=(
            "Presidio's NLP-based recognizer identified this text as a "
            "location with sufficient confidence."
        ),
        developer_mistake=(
            "Reusing a real customer address in a fixture instead of a "
            "synthetic one."
        ),
        security_impact=(
            "Location data tied to a named individual is sensitive PII "
            "and can enable physical-safety risks if leaked."
        ),
    ),
    "US_DRIVER_LICENSE": _EntityNarrative(
        root_cause=(
            "A U.S. driver's license number was committed directly into "
            "source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched a value "
            "structurally consistent with a driver's license number."
        ),
        developer_mistake=(
            "Reusing a real individual's license number for identity "
            "verification test fixtures."
        ),
        security_impact=(
            "Driver's license numbers are a common secondary identity "
            "document used in identity-theft and fraud schemes."
        ),
    ),
    "URL": _EntityNarrative(
        root_cause=(
            "A URL embedded in source or configuration may contain "
            "credentials, internal-only hostnames, or other "
            "environment-specific detail that does not belong in code."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched standard URL "
            "syntax."
        ),
        developer_mistake=(
            "Hardcoding an environment-specific or credentialed URL "
            "instead of building it from configuration/secrets at "
            "runtime."
        ),
        security_impact=(
            "URLs containing embedded credentials or internal hostnames "
            "can leak access or aid reconnaissance if the repository is "
            "exposed."
        ),
    ),
    "DATE_TIME": _EntityNarrative(
        root_cause=(
            "A specific date (potentially a date of birth or other "
            "individual-linked date) was left in source or test data."
        ),
        why_detected=(
            "Presidio's pattern-based recognizer matched standard date/"
            "time syntax."
        ),
        developer_mistake=(
            "Reusing a real individual's date (e.g. date of birth) in a "
            "fixture instead of a synthetic date."
        ),
        security_impact=(
            "A date of birth tied to a named individual is a common "
            "identity-verification data point and increases "
            "identity-theft risk when exposed alongside other findings."
        ),
    ),
    "NRP": _EntityNarrative(
        root_cause=(
            "Text referencing a nationality, religious, or political "
            "affiliation tied to an individual was left in source or "
            "test data."
        ),
        why_detected=(
            "Presidio's NLP-based recognizer identified this text as a "
            "nationality/religious/political reference with sufficient "
            "confidence."
        ),
        developer_mistake=(
            "Including real, individual-linked demographic detail in an "
            "example or test fixture."
        ),
        security_impact=(
            "This category can constitute special-category/sensitive "
            "personal data under regulations such as GDPR, carrying "
            "elevated compliance risk if exposed."
        ),
    ),
}


def narrative_for_entity(entity_type: str) -> _EntityNarrative:
    """Return the static root-cause narrative for a Presidio entity type."""
    return _ENTITY_NARRATIVES.get(entity_type, _DEFAULT_NARRATIVE)


class RootCauseEngine:
    """Derives a deterministic root-cause analysis for each finding."""

    def analyze_finding(self, finding: dict[str, Any]) -> dict[str, Any]:
        """
        Build the root-cause analysis for a single finding.

        Args:
            finding: A single finding dict from a Task 2 Phase 1 JSON
                report's `findings` list (ideally already enriched with
                a `finding_id`, see `scanner.intelligence.finding_ids`).

        Returns:
            A dict with `finding_id`, `entity_type`, `severity`, `file`,
            `line_number`, `category`, `confidence` (the detection
            confidence already computed by Presidio -- never a new,
            fabricated score), `root_cause`, `why_detected`,
            `likely_developer_mistake`, and `security_impact`.
        """
        entity_type = finding.get("entity_type", "UNKNOWN")
        narrative = narrative_for_entity(entity_type)
        category = categorize_entity(entity_type)

        return {
            "finding_id": finding.get("finding_id"),
            "entity_type": entity_type,
            "severity": finding.get("severity"),
            "category": category.value,
            "file": finding.get("file"),
            "line_number": finding.get("line_number"),
            "confidence": finding.get("confidence_score"),
            "root_cause": narrative.root_cause,
            "why_detected": narrative.why_detected,
            "likely_developer_mistake": narrative.developer_mistake,
            "security_impact": narrative.security_impact,
        }

    def analyze_findings(self, findings: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """
        Build root-cause analyses for every finding in a report.

        Args:
            findings: The `findings` list from a Task 2 Phase 1 JSON
                report (finding IDs are attached automatically if not
                already present).

        Returns:
            A list of root-cause analysis dicts (see
            `analyze_finding`), one per input finding, in the same
            order.
        """
        if findings and "finding_id" not in findings[0]:
            findings = attach_finding_ids(findings)
        return [self.analyze_finding(finding) for finding in findings]
